export const LOGIN_START = 'LOGIN_START';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE =  'LOGIN_FAILURE';

export const LOGOUT_START = 'LOGIN_START';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS'

export const FORGOT_PWD_START = 'FORGOT_PWD_START';
export const FORGOT_PWD_SUCCESS = 'FORGOT_PWD_SUCCESS';
export const FORGOT_PWD_FAILURE = 'FORGOT_PWD_FAILURE';

export const RESET_PWD_START = 'RESET_PWD_START';
export const RESET_PWD_SUCCESS = 'RESET_PWD_SUCCESS';
export const RESET_PWD_FAILURE = 'RESET_PWD_FAILURE';
