export const GET_USERS_START = 'GET_USERS_START';
export const GET_USERS_SUCCESS = 'GET_USERS_SUCCESS';
export const GET_USERS_FAILURE =  'GET_USERS_FAILURE';

export const ADD_USER_START = 'ADD_USERS_START';
export const ADD_USER_SUCCESS = 'ADD_USERS_SUCCESS';
export const ADD_USER_FAILURE =  'ADD_USERS_FAILURE';


export const UPDATE_USER_START = 'UPDATE_USER_START';
export const UPDATE_USER_SUCCESS = 'UPDATE_USER_SUCCESS';
export const UPDATE_USER_FAILURE =  'UPDATE_USER_FAILURE';

export const DELETE_USER_START = 'DELETE_USER_START';
export const DELETE_USER_SUCCESS = 'DELETE_USER_SUCCESS';
export const DELETE_USER_FAILURE =  'DELETE_USER_FAILURE';
